## build : docker build -t openair4g .
## run :   docker run --net=host --rm --privileged -v /dev/bus/usb:/dev/bus/usb -it openair4g
## run your own config and with a PCAP :   docker run --rm --net=host --privileged -v /dev/bus/usb:/dev/bus/usb -v /YOURCONFIGDIRECTORY:/root --entrypoint /openairinterface5g/targets/bin/lte-softmodem.Rel14 openair4g -P /root/capture.pcap  -O /root/enb.conf

FROM ubuntu:16.04
MAINTAINER Tejas Subramanya <tejas.sln89@gmail.com>
ENV DEBIAN_FRONTEND noninteractive
#RUN apt-get update
#RUN apt-get -yq dist-upgrade 

# Dependencies for the UHD driver for the USRP hardware
RUN apt-get update && \
    apt-get -yq dist-upgrade && \
    apt-get -yq install autoconf build-essential libusb-1.0-0-dev cmake wget pkg-config libboost-all-dev python-dev python-cheetah git subversion python-software-properties

# Dependencies for UHD image downloader script
RUN apt-get -yq install python-mako python-requests 

# Fetching the uhd 3.010.001 driver for our USRP SDR card 
RUN wget http://files.ettus.com/binaries/uhd/uhd_003.010.001.001-release/uhd-3.10.1.1.tar.gz && tar xvzf uhd-3.10.1.1.tar.gz && cd UHD_3.10.1.1_release && mkdir build && cd build && cmake ../ && make && make install && ldconfig && python /usr/local/lib/uhd/utils/uhd_images_downloader.py

# Dependencies for SRSeNB
RUN apt-get -yq --no-install-recommends --assume-yes install libfftw3-dev libmbedtls-dev libboost-all-dev libconfig++-dev libsctp-dev 

# Fetching the latest repository and Building the srslte eNB for USRP
RUN git clone https://github.com/srsLTE/srsLTE.git && cd srsLTE && mkdir build && cd build && cmake ../ && make && make install && ldconfig

# Add a sample configuration file
ADD enb.conf /srsLTE/build/srsenb/src/enb.conf
ADD drb.conf /srsLTE/build/srsenb/src/drb.conf
ADD rr.conf /srsLTE/build/srsenb/src/rr.conf
ADD sib.conf /srsLTE/build/srsenb/src/sib.conf

# Run directly the eNodeB code 
ENTRYPOINT ./srsLTE/build/srsenb/src/srsenb /srsLTE/build/srsenb/src/enb.conf
